version: 0.0
os: windows
files:
  - source: /
    destination: C:\inetpub\wwwroot
hooks:
  BeforeInstall:
    - location: \StopWebsite.ps1
      timeout: 300
  AfterInstall:
    - location: \StartWebsite.ps1
      timeout: 300
