version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 6.0
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore
  build:
    commands:
      - echo Build started on `date`
      - dotnet build --configuration Release
  post_build:
    commands:
      - echo Publish started on `date`
      - dotnet publish --configuration Release --output ./publish_output

artifacts:
  files:
    - './publish_output/**/*'
  discard-paths: yes
